menu_sections:
  global_admin: "Globalny administrator"
  facility: "Plac贸wka"
  facility_admin: "Administrator plac贸wki"
  other: "Inne"

login: "logowanie"

admin:
  facilities: "$t(models.facility._name_plural)"
  users: "$t(models.user._name_plural)"

facility:
  home: "plac贸wka"
  calendar: "$t(calendar.calendar)"
  meetings: "$t(models.meeting._name_plural)"
  meeting_attendants: "$t(models.meeting.attendants)"
  meeting_clients: "$t(tables.tables.meeting_client.table_name)"
  staff: "$t(models.staff._name_plural)"
  staff_details: "$t(models.staff._name)"
  clients: "$t(models.client._name_plural)"
  client_details: "$t(models.client._name)"
  client_create: "$t(forms.client_create.formName)"
  admins: "administratorzy"

  facility_admin:
    time_tables: "grafiki pracy"
    time_tables_staff: "pracownicy"
    time_tables_facility: "plac贸wka"
    reports: "raporty"

help: "pomoc"
help_pages:
  about: "informacje o Memo"
