menu_sections:
  global_admin: "Globalny administrator"
  facility: "Placówka"
  facility_admin: "Administrator"
  other: "Inne"

login: "logowanie"

admin:
  facilities: "$t(models.facility._name_plural)"
  users: "$t(models.user._name_plural)"

facility:
  home: "placówka"
  calendar: "$t(calendar.calendar)"
  meetings: "$t(models.meeting._name_plural)"
  meeting_series: "seria spotkań"
  meeting_attendants: "$t(models.meeting.attendants)"
  meeting_clients: "$t(tables.tables.meeting_client.table_name)"
  staff: "$t(models.staff._name_plural)"
  staff_details: "$t(models.staff._name)"
  clients: "$t(models.client._name_plural)"
  client_details: "$t(models.client._name)"
  client_create: "$t(forms.client_create.form_name)"
  admins: "administratorzy"
  leave_times: "nieobecności"

  facility_admin:
    time_tables: "grafiki pracy"
    time_tables_calendar: "kalendarz"
    time_tables_weekly: "grafiki tygodniowe"
    reports: "raporty"
    notifications: "powiadomienia"

help: "pomoc"
help_pages:
  about: "informacje o Memo"
