#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

(function (string $basePath): never {
    /** @var Illuminate\Foundation\Application $app */
    $app = require_once "$basePath/bootstrap/app.php";
    $status = $app->handleCommand(new ArgvInput());
    exit($status);
})(
    basePath: __DIR__
);
