export const NOTIFICATION_REASONS_MAP = {
  Chronic_or_sudden_illness__c: "przewlekła lub nagła choroba",
  Concerns_about_child_s_development__c: "niepokój zw. z nieprawidłowym rozwojem",
  Death_in_the_family__c: "śmierć w rodzinie",
  Disturbing_child_s_behavior__c: "niepokojące zachowania dziecka",
  Divorce__c: "rozwód",
  early_parenthood__c: "wczesne rodzicielstwo",
  Emotional_coldness__c: "chłód emocjonalny",
  Impaired_relationship_with_a_child__c: "zaburzona więź z dzieckiem",
  Lack_of_consequence__c: "brak konsekwencji w postępowaniu z dzieckiem",
  Lack_of_interest_in_a_child__c: "brak zainteresowania dzieckiem",
  Leave_child_unattended__c: "pozostawienie bez opieki",
  No_reaction_to_a_crying_child__c: "brak reakcji na płacz dziecka",
  Problems_of_communication_with_child__c: "kłopoty w komunikacji z dzieckiem",
  Problems_of_coping_with_child_s_emotions__c: "trudność w radzeniu sobie z emocjami dziecka",
  Problems_of_recognizing_child_s_needs__c: "trudność w rozpoznawaniu potrzeb dziecka",
  Problems_of_separation_with_a_child__c: "zaburzona więź separacyjna",
  Problems_of_setting_boundaries__c: "trudności w stawianiu granic",
  Problem_of_coping_with_your_own_emotions__c: "problem z radzeniem sobie z własnymi emocjami",
  Reconstructed_family__c: "rodzina rekonstruowana",
  Separation__c: "separacja",
  Single_parenthood__c: "samotne rodzicielstwo",
  Too_high_expectations_towards_a_child__c: "zbyt wysokie oczekiwania wobec dziecka",
  Unplanned_pregnancy__c: "nieplanowana ciąża",
} as const;
