export const SURVEY_FIELDS = [
  {
    group: "Sytuacja ekonomiczna",
    items: [
      {label: "trudna sytuacja materialna", field: "Difficult_financial_situation__c"},
      {label: "trudna sytuacja mieszkaniowa", field: "Difficult_housing_situation__c"},
    ],
  },
  {
    group: "Sytuacja rodzinna",
    items: [
      {label: "wielodzietność", field: "Families_with_many_children__c"},
      {label: "inne dzieci w pieczy zastępczej", field: "Other_children_in_foster_care__c"},
      {label: "samotne rodzicielstwo", field: "Lone_parenthood__c"},
      {label: "interwencje policji", field: "Police_intervention__c"},
      {label: "rodzina zastępcza", field: "Foster_family__c"},
      {label: "konflikty w rodzinie", field: "Conflicts_in_the_family__c"},
      {label: "partner niebędący rodzicem biol. dziecka", field: "Partner_is_not_a_biol_parent_of_a_child__c"},
      {label: "rozwód w rodzinie", field: "Divorce_in_the_family__c"},
      {label: "rodzina adopcyjna", field: "Adoptive_family__c"},
      {label: "przemoc między dorosłymi w rodzinie", field: "Violence_between_adults_in_the_family__c"},
      {label: "uzależnienia w rodzinie", field: "Addictions_in_the_family__c"},
      {label: "przemoc wobec dzieci w rodzinie", field: "Violence_against_children_in_the_family__c"},
      {label: "przewlekła choroba członka rodziny", field: "Chronic_illness_of_a_family_member__c"},
      {label: "dzieci z różnych związków", field: "Children_from_different_compounds__c"},
    ],
  },
  {
    group: "Rodzice",
    items: [
      {label: "odmienność kulturowa/religijna", field: "Otherness_culture_religo__c"},
      {label: "niezdolność radzenia sobie z zach. dz.", field: "Inability_to_cope_with_child_s_behavior__c"},
      {label: "izolacja, unikanie kontaktu", field: "Insulation_avoiding_contact__c"},
      {label: "nadopiekuńczość", field: "Overprotection__c"},
      {label: "agresja w stosunku do dorosłych", field: "Aggression_towards_adults__c"},
      {label: "niepełnosprawność intelektualna rodzica", field: "Intellectual_disability_of_parent__c"},
      {label: "agresja w stosunku do dziecka", field: "Aggression_against_a_child__c"},
      {label: "brak wiedzy nt. rozwoju dziecka", field: "Lack_of_knowledge_about_child_developmen__c"},
      {label: "stwierdzone zaburzenia psychiczne", field: "Identified_mental_disorders__c"},
      {label: "nieletni rodzice", field: "Juvenile_parents__c"},
      {label: "zaniedbywanie potrzeb fiz. dziecka", field: "Neglecting_physical_needs_of_child__c"},
      {label: "doświadczenia przemocy w dzieciństwie", field: "The_experience_of_violence_in_childhood__c"},
      {label: "zaniedbywanie potrzeb psych. dziecka", field: "Neglecting_mental_needs_of_child__c"},
      {label: "przewlekła choroba jednego z rodziców", field: "Chronic_illness_one_of_the_parents__c"},
      {label: "ograniczony kontakt z dzieckiem", field: "Limited_contact_with_child__c"},
      {label: "brak gotowości do podjęcia roli rodzica", field: "Not_ready_to_take_the_role_of_a_parent__c"},
      {label: "trudny poród", field: "A_difficult_childbirth__c"},
      {label: "rodzice zbyt obciążeni obowiązkami", field: "Parents_too_overwhelmed_with_duties__c"},
      {label: "brak opieki medycznej podczas ciąży", field: "Lack_of_medical_care_during_pregnancy__c"},
      {label: "karalność rodziców", field: "Parent_s_penality__c"},
      {label: "stosowanie niekonstruktywnych metod", field: "Using_unconstructive_methods__c"},
      {label: "zaniedbanie medyczne", field: "Medical_neglect__c"},
    ],
  },
  {
    group: "Dziecko",
    items: [
      {label: "dziecko o szczególnych potrzebach", field: "High_need_child__c"},
      {label: "zaburzony rozwój społeczny dziecka", field: "Child_s_impaired_social_development__c"},
      {label: "niechciane dziecko", field: "Unwanted_child__c"},
      {label: "zaburzony rozwój emocjonalny dziecka", field: "Child_s_impaired_emotional_development__c"},
      {label: "niepełnosprawne dziecko", field: "Disabled_child__c"},
      {label: "niepokojąca relacja rodzic - dziecko", field: "Disturbing_relation_of_parent_and_child__c"},
      {label: "chorowite dziecko", field: "Sickly_child__c"},
      {label: "zaburzony rozwój psychomotoryczny dz.", field: "Child_s_impaired_psychomotor_development__c"},
    ],
  },
] as const;
