export const SURVEY_FIELDS = [
  {
    group: "Sytuacja ekonomiczna",
    items: [
      {label: "Trudna sytuacja materialna", field: "Difficult_financial_situation__c"},
      {label: "Trudna sytuacja mieszkaniowa", field: "Difficult_housing_situation__c"},
    ],
  },
  {
    group: "Sytuacja rodzinna",
    items: [
      {label: "Wielodzietność", field: "Families_with_many_children__c"},
      {label: "Inne dzieci w pieczy zastępczej", field: "Other_children_in_foster_care__c"},
      {label: "Samotne rodzicielstwo", field: "Lone_parenthood__c"},
      {label: "Interwencje policji", field: "Police_intervention__c"},
      {label: "Rodzina zastępcza", field: "Foster_family__c"},
      {label: "Konflikty w rodzinie", field: "Conflicts_in_the_family__c"},
      {label: "Partner niebędący rodzicem biol. dziecka", field: "Partner_is_not_a_biol_parent_of_a_child__c"},
      {label: "Rozwód w rodzinie", field: "Divorce_in_the_family__c"},
      {label: "Rodzina adopcyjna", field: "Adoptive_family__c"},
      {label: "Przemoc między dorosłymi w rodzinie", field: "Violence_between_adults_in_the_family__c"},
      {label: "Uzależnienia w rodzinie", field: "Addictions_in_the_family__c"},
      {label: "Przemoc wobec dzieci w rodzinie", field: "Violence_against_children_in_the_family__c"},
      {label: "Przewlekła choroba członka rodziny", field: "Chronic_illness_of_a_family_member__c"},
      {label: "Dzieci z różnych związków", field: "Children_from_different_compounds__c"},
    ],
  },
  {
    group: "Rodzice",
    items: [
      {label: "Odmienność kulturowa/religijna", field: "Otherness_culture_religo__c"},
      {label: "Niezdolność radzenia sobie z zach. dz.", field: "Inability_to_cope_with_child_s_behavior__c"},
      {label: "Izolacja, unikanie kontaktu", field: "Insulation_avoiding_contact__c"},
      {label: "Nadopiekuńczość", field: "Overprotection__c"},
      {label: "Agresja w stosunku do dorosłych", field: "Aggression_towards_adults__c"},
      {label: "Niepełnosprawność intelektualna rodzica", field: "Intellectual_disability_of_parent__c"},
      {label: "Agresja w stosunku do dziecka", field: "Aggression_against_a_child__c"},
      {label: "Brak wiedzy nt. rozwoju dziecka", field: "Lack_of_knowledge_about_child_developmen__c"},
      {label: "Stwierdzone zaburzenia psychiczne", field: "Identified_mental_disorders__c"},
      {label: "Nieletni rodzice", field: "Juvenile_parents__c"},
      {label: "Zaniedbywanie potrzeb fiz. dziecka", field: "Neglecting_physical_needs_of_child__c"},
      {label: "Doświadczenia przemocy w dzieciństwie", field: "The_experience_of_violence_in_childhood__c"},
      {label: "Zaniedbywanie potrzeb psych. dziecka", field: "Neglecting_mental_needs_of_child__c"},
      {label: "Przewlekła choroba jednego z rodziców", field: "Chronic_illness_one_of_the_parents__c"},
      {label: "Ograniczony kontakt z dzieckiem", field: "Limited_contact_with_child__c"},
      {label: "Brak gotowości do podjęcia roli rodzica", field: "Not_ready_to_take_the_role_of_a_parent__c"},
      {label: "Trudny poród", field: "A_difficult_childbirth__c"},
      {label: "Rodzice zbyt obciążeni obowiązkami", field: "Parents_too_overwhelmed_with_duties__c"},
      {label: "Brak opieki medycznej podczas ciąży", field: "Lack_of_medical_care_during_pregnancy__c"},
      {label: "Karalność rodziców", field: "Parent_s_penality__c"},
      {label: "Stosowanie niekonstruktywnych metod", field: "Using_unconstructive_methods__c"},
      {label: "Zaniedbanie medyczne", field: "Medical_neglect__c"},
    ],
  },
  {
    group: "Dziecko",
    items: [
      {label: "Dziecko o szczególnych potrzebach", field: "High_need_child__c"},
      {label: "Zaburzony rozwój społeczny dziecka", field: "Child_s_impaired_social_development__c"},
      {label: "Niechciane dziecko", field: "Unwanted_child__c"},
      {label: "Zaburzony rozwój emocjonalny dziecka", field: "Child_s_impaired_emotional_development__c"},
      {label: "Niepełnosprawne dziecko", field: "Disabled_child__c"},
      {label: "Niepokojąca relacja rodzic - dziecko", field: "Disturbing_relation_of_parent_and_child__c"},
      {label: "Chorowite dziecko", field: "Sickly_child__c"},
      {label: "Zaburzony rozwój psychomotoryczny dz.", field: "Child_s_impaired_psychomotor_development__c"},
    ],
  },
] as const;
